### ISSUE TITLE
Failed to execute child process "bash": Failed to fdwalk: Operation not permitted

### ISSUE THREAD

**Issue by hannibalpostumus** [Aterfax/DCS-World-Dedicated-Server-Docker#29]
On launching the DCS Installer Desktop script (or a terminal for that matter), the following error message appears: 

**Failed to execute child process "shell": Failed to fdwalk: Operation not permitted**

This seems to be a known bug in many X11 docker terminals such as [here](https://github.com/mviereck/x11docker/issues/346) and [here](https://gitlab.xfce.org/apps/xfce4-terminal/-/issues/116).

The agreed solution is to set the security_opt option to unconfined. I have made a new [pull request](https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/pull/28) with the change inside the docker compose that has fixed this.

**Comment by Aterfax** [comment]
Resolved in https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/pull/30

Ty for highlighting this.
