### ISSUE TITLE
 Open Beta MD5 check fails

### ISSUE THREAD

**Issue by TheDelta** [Aterfax/DCS-World-Dedicated-Server-Docker#43]
Currently trying to setup this container and DCS recently announced that open beta will be removed. (unified release).

Atm it tries to download `https://www.digitalcombatsimulator.com/upload/iblock/ebb/2krwumwaj6vakg2gny13g1t56jral5nq/DCS_World_OpenBeta_Server_modular.exe` which works, but the MD5 check will fail because the site has been taken down already :(

(https://www.digitalcombatsimulator.com/en/downloads/world/server_beta/ -> error)

**Comment by Aterfax** [comment]
Resolving this shortly.

**Comment by TheDelta** [comment]
Thanks for being so quick. 👍  I used my own fork to continue with the server setup.
Might make sense for the future to remove other mentions of Open Beta as well (currently the installation is moved into a path which still contains Open Beta, etc.):
```bash
cd /config && innoextract -e -m DCS_World_OpenBeta_Server_modular.exe
mkdir -p "/config/.wine/drive_c/Program Files/Eagle Dynamics/DCS World OpenBeta Server"
mv app/* "/config/.wine/drive_c/Program Files/Eagle Dynamics/DCS World OpenBeta Server/" && rmdir app
cd "/config/.wine/drive_c/Program Files/Eagle Dynamics/DCS World OpenBeta Server/bin"

```
Eventually should migrate older installs (simply mv and update shortcuts) would be enough probably.

**Comment by Aterfax** [comment]
Eventually I will have a bit more time to go in and add the logic to support the older and newer directories. But I have not decided on an approach yet.
