### ISSUE TITLE
Autoinstall Desktop Shortcuts

### ISSUE THREAD

**Issue by BrotRooti** [Aterfax/DCS-World-Dedicated-Server-Docker#53]
The Shortcut for DCS Saved Games Directory, wich is created by the autoinstaller, is still mapped to the **.openbeta_server**, wich does not exist on new installs, instead of the **.realese_server**

**Comment by BrotRooti** [comment]
The same problem exists with the autostart script, so there is likely a problem with the function, wich selects the right pahts

**Comment by Aterfax** [comment]
Hi, please see https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/blob/7e2f57a7aa4b06dcc3e6f9b37cca813360bb2f64/docker/src/s6-services/s6-init-migrate-dcs-oneshot/run#L26

This release isn't out until Saturday so this won't take effect yet.

**Comment by Aterfax** [comment]
I will close this out for now as I think this is invalid. If this is still an issue with the image when it generates this coming Saturday please let me know and I will re-open and investigate.
