### ISSUE TITLE
DCS World Does not login properly after todays update: 2.9.4.53990

### ISSUE THREAD

**Issue by afinegan** [Aterfax/DCS-World-Dedicated-Server-Docker#61]
DCS World Does not login properly after todays update: 2.9.4.53990

I am trying to figx the issue, I updated the gzip package and its still throwing the same error - it seems like ED changed something in there login auth package file....

<img width="930" alt="image" src="https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/assets/6625755/4982f744-893f-4823-8cdb-86c7485b24a6">

Bad auth data: Gunzip: header decoding error --- the version of gzip on my windows box is 1.10 and the one on alpine is 1.13... so I dont think its that, I am not sure what to do at this point

**Comment by tspindler-cms** [comment]
The DCS FAQ lists something about incorrect time on the system:
https://www.digitalcombatsimulator.com/en/support/faq/authorization/#3314963
But I have some doubts that this is the core reason behind it.

**Comment by afinegan** [comment]
> The DCS FAQ lists something about incorrect time on the system: https://www.digitalcombatsimulator.com/en/support/faq/authorization/#3314963 But I have some doubts that this is the core reason behind it.

Ya, I installed ntp - synced the date on the box, checked the date in the docker, checked the date in "wine cmd" + "time" and it all matches up. I started with UTC for all of it, then switched it to America/New_York  across the board and they all sync correctly. The code was working find prepatch, gzip version on windows is 1.10 and on the box is 1.13 - Still trying to figure it out, because I dont want to run windows - it ran the DDCS echo system flawlessly last night and I truly want to get it to work (just done with windows servers if I can help it). I cant be the only person with this issue

**Comment by tspindler-cms** [comment]
I face the same issue, forgot to mention this in my post. Linux host is Ubuntu 22.04 LTS and system time set to UTC as well.

**Comment by Aterfax** [comment]
Had a look. I have no way to debug or fix this error because I have no visibility over what changed or why the auth response may now be garbled. 

The fix for this will lie with Eagle Dynamics either fixing something on their end or giving me enough info on what changed to figure out a fix.

**Comment by Aterfax** [comment]
Hmm, I may have found a fix - although I cannot comment exactly on why this works... Call it an informed guess, smh...

1. Open a terminal in the container webGUI, run the command ``winecfg`` and navigate to the libraries tab.
2. Add a new override for a library called ``wbemprox``.
3. Select it and hit the edit button.
4. Set it to ``Native (Windows)``
5. Hit the Ok button.
6. Hit the ok button on the ``winecfg`` parent window.
7. Try running the server and it should open.

Let me know if this fixes the issue, if a bunch of you confirm it I will look at amending the container code to make this the default setting.

**Comment by tspindler-cms** [comment]
Works for me, thanks a lot! Kola here we come!

![image](https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/assets/5772983/717afb24-9f4a-4586-8a73-a3d7a1b5344d)

**Comment by Aterfax** [comment]
Righto, I will if I can get this hotfixed relatively fast then.

**Comment by Aterfax** [comment]
This is now merged above so folks do let me know if this doesn't fully resolve the problem or you think you might be having any issues related to the fix. Have fun over the Kola!
