### ISSUE TITLE
HTTP 404 for DCS_World_Server_modular.exe

### ISSUE THREAD

**Issue by TheDelta** [Aterfax/DCS-World-Dedicated-Server-Docker#65]
Tried the latest version and it seems like that the download url is not valid anymore:

https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/blob/3155048a9a775d1c1d0ecf2c4edb6c5e44d8fda5/docker/src/s6-services/s6-init-getlatest-dcs-installer-oneshot/run#L42

gives me a 404 and server install will fail.
I remember in the past that there was some code to go the download page and extract the download link from the page.

Download link is now `https://www.digitalcombatsimulator.com/upload/iblock/17c/slq6u1srmqqi1fb2oaofz1qx6vc5p2fh/DCS_World_Server_modular.exe` (according to https://www.digitalcombatsimulator.com/en/downloads/world/server/)

Ironic that I run into a similar issue once again :D
Maybe some sort of environment variable as fallback would make sense? (and of course the html extract to get the DL url - I assume ED will update the link from time for time...)

To fix it with current version (1.0) simply download the file and put it into the `config` root folder (the file should be present with 0kb and must be replaced with the downloaded one)
Then it will work 👍

**Comment by Aterfax** [comment]
Hotfixing this for now, but will have a look at updating it to determine the link in the same way as the MD5 sum.

**Comment by Aterfax** [comment]
This should be resolved by another image pull when this run finishes - https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/actions/runs/8974090795/job/24645680756

**Comment by TheDelta** [comment]
thanks again for the fast fix 🚀 ❤️

**Comment by Aterfax** [comment]
Also sorted more dynamic link lookup logic in https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/pull/68
