### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by HiveLeader** [Aterfax/DCS-World-Dedicated-Server-Docker#80]
I got a very low download speed of the dcs server files. Downloading the "Delta Index" takes forever. Now Iam downloading the files with around 100 KB/s. My speedtest matchs my wan speed and pinging some important IPs seems ok.

Can anyone help me ?

![Screenshot 2024-07-14 164945](https://github.com/user-attachments/assets/d09675ee-67f8-4c68-a087-9062e58e7747)
[Log.txt](https://github.com/user-attachments/files/16227825/Log.txt)

**Comment by Aterfax** [comment]
Seems likely to be DCS CDN / servers being slow giving your first lines in the log output. Especially since the speed test inside the container is showing good values.

**Comment by Aterfax** [comment]
Closing this ticket unless a consistent lack of speed is happening. Please let me know if that is the case and re-open.

**Comment by pootislord** [comment]
I ran into this problem too, I thought at first it was something to do with the docker network breaking DCS's P2P update protocol so I ran it on host mode to see if that would help, but it didn't seem to make a difference. similarly to @HiveLeader I was also getting gig down in the browser. In the end I settled for using a dcs_local_source.txt so it could pull the files from my PC on the network.
