### ISSUE TITLE
Failed to open terminal in docker

### ISSUE THREAD

**Issue by Yarkinco** [Aterfax/DCS-World-Dedicated-Server-Docker#82]
Hello,

I tried to setup this server but I got this error when I tried to execute the Run First DCS Install on webgui.

Any idea whats the problem?

![resim](https://github.com/user-attachments/assets/fac12577-8e69-42b9-bc9f-cf78f8f55210)

**Comment by Aterfax** [comment]
Please see this link: https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker?tab=readme-ov-file#failed-to-fdwalk-operation-not-permitted-errors
