### ISSUE TITLE
Modules list regex does not allow

### ISSUE THREAD

**Issue by CC1337** [Aterfax/DCS-World-Dedicated-Server-Docker#88]
According to the readme/error message on the ENV variable DCS_MODULKES it expects a whitespace separated list and does not allow a hyphen. However, on the linked module list https://forum.dcs.world/topic/324040-eagle-dynamics-modular-dedicated-server-installer/
"WWII-ARMOUR" contains a hyphen.

Not sure if this module is needed for anyone, but if so, the regex might need adjustments.

https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/blob/893c6e27e2bace413d5119cf2082e460dda7c6e6/docker/src/wine-dedicated-dcs-automated-installer/dcs-dedicated-server-automatic-installer.sh#L47
https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/blob/893c6e27e2bace413d5119cf2082e460dda7c6e6/docker/src/wine-dedicated-dcs-automated-installer/dcs-dedicated-server-module-installer.sh#L31

**Comment by Aterfax** [comment]
It's whitespace separated but yes, the omission of a hyphen also being valid is a bug.

**Comment by CC1337** [comment]
oops, yes of course whitespace separated. I did so in my setup, just wrote the ticket wrong. I fixed it above!
