### ISSUE TITLE
unable to start service init-getlatest-dcs-installer-oneshot: command exited 1

### ISSUE THREAD

**Issue by rgpollitt** [Aterfax/DCS-World-Dedicated-Server-Docker#90]
Hi,

Installed this last weekend and it was working beautifully.

Now , today when starting up the docker container it gives me the following message in my DockGE terminal:

"
[s6-init-getlatest-dcs-installer-oneshot] Error occurred (Exit code: 1)
dcs-server    | s6-rc: warning: unable to start service init-getlatest-dcs-installer-oneshot: command exited 1
"

Used to see confirmations in the DockGE terminal that server is alive. Those messages are also not there.

Have AUTOSTART as AUTOSTART=1. When checking the status via Alpine XFCE, the DCS Server however has not started up.  When clicking on the start server icon on desktop , the DCS Server splash screen appears. But when trying to connect via WebGUI it says "Server not responding"

**Comment by Aterfax** [comment]
As the DCS website isn't loading / is very slow for me, Eagle Dynamic's servers may be having some issues.

**Comment by rgpollitt** [comment]
Wow, that's a quick response :-)  DCS client also very slow when retrieving list of available MP servers.   Probably ED servers then indeed

**Comment by rgpollitt** [comment]
ED servers issue
